services:
  redis:
    image: redis:7
    ports: ["6380:6379"]            # usa 6380 si 6379 está ocupado

  trainer:
    build:
      context: .                    # ← raíz del repo
      dockerfile: cmd/trainer/Dockerfile
    depends_on: [redis]

  predictor:
    build:
      context: .                    # ← raíz del repo
      dockerfile: cmd/predictor/Dockerfile
    depends_on: [redis]
    ports: ["8080:8080"]
